#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Raya Elena Solano
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render docs/dbus-api.md from interfaces/*.xml + docs/dbus-descriptions.toml, and audit that EVERY member has a
description (RQ-3: an API-first project must document 100 % of its contract).

  tools/dbus-doc.py            # audit only: exit 1 and list undocumented members
  tools/dbus-doc.py --write    # (re)generate docs/dbus-api.md

Descriptions live in one TOML file keyed "Interface.Member" so a new member fails the build until someone writes the
sentence — the same principle as sot-audit for requirements.
"""
import sys, tomllib, pathlib, xml.etree.ElementTree as ET

root = pathlib.Path(__file__).resolve().parent.parent
desc = tomllib.loads((root / "docs/dbus-descriptions.toml").read_text())
ORDER = ["Mixer", "Channel", "Mix", "Cell", "App", "Levels"]
SIG = {"s": "string", "b": "bool", "d": "double", "i": "int32", "u": "uint32", "o": "object path", "as": "string[]",
       "ao": "object path[]", "a{ss}": "dict<string,string>", "a{sd}": "dict<string,double>", "a{sv}": "dict<string,variant>"}
def ty(t): return SIG.get(t, f"`{t}`")

out, missing, total = [], [], 0
out.append("# D-Bus API — `org.kmixdeck1`\n")
out.append("<!-- GENERATED by tools/dbus-doc.py from interfaces/*.xml and docs/dbus-descriptions.toml — edit those, not this. -->\n")
out.append("The service `org.kmixdeck1` on the **session bus** exports one object tree under `/org/kmixdeck1`, browsable with "
           "`org.freedesktop.DBus.ObjectManager` (`GetManagedObjects` returns everything in one call; `InterfacesAdded/Removed` "
           "announce changes). Every object also implements `org.freedesktop.DBus.Properties`, and every property change is "
           "signalled with `PropertiesChanged` — a frontend never polls.\n")
out.append("| Path | Interface | One per |\n|---|---|---|\n"
           "| `/org/kmixdeck1` | `Mixer` | service |\n| `/org/kmixdeck1/channel/<slug>` | `Channel` | channel |\n"
           "| `/org/kmixdeck1/mix/<slug>` | `Mix` | mix |\n| `/org/kmixdeck1/cell/<channel>/<mix>` | `Cell` | channel × mix |\n"
           "| `/org/kmixdeck1/app/<id>` | `App` | application stream |\n| `/org/kmixdeck1/levels` | `Levels` | service |\n")
out.append("**Conventions.** Levels are linear 0…1 (1 = unity, 0 = −∞) unless a member says dB. Slugs are the lower-cased, "
           "ASCII-folded names. Device references (`<ref>`) follow the grammar `node.name[:PORT[,PORT]][>L|>R]` "
           "(ADR 0009). Methods that refuse throw `org.kmixdeck1.Error.Rejected` with a human-readable message; the CLI maps "
           "that to exit code 4. Everything the daemon accepts is persisted to `layout.json` and rendered to the PipeWire "
           "config before the call returns.\n")
out.append("The introspection XML in [`interfaces/`](../interfaces/) is the checked contract; this page is its prose.\n")

for name in ORDER:
    f = root / f"interfaces/org.kmixdeck1.{name}.xml"
    iface = next(i for i in ET.parse(f).getroot().iter("interface"))
    out.append(f"\n## `{iface.get('name')}`\n")
    intro = desc.get(name, {}).get("_intro")
    if intro: out.append(intro.strip() + "\n")
    for kind, title in (("property", "Properties"), ("method", "Methods"), ("signal", "Signals")):
        members = [m for m in iface if m.tag == kind]
        if not members: continue
        out.append(f"\n### {title}\n")
        if kind == "property": out.append("| Name | Type | Access | Meaning |\n|---|---|---|---|\n")
        else: out.append("| Name | Signature | Meaning |\n|---|---|---|\n")
        for m in members:
            total += 1
            key = f"{name}.{m.get('name')}"
            d = desc.get(name, {}).get(m.get("name"))
            if not d: missing.append(key); d = "**UNDOCUMENTED**"
            d = d.strip().replace("\n", " ").replace("|", "\\|")
            if kind == "property":
                out.append(f"| `{m.get('name')}` | {ty(m.get('type'))} | {m.get('access')} | {d} |\n")
            else:
                ins = ", ".join(f"{a.get('name') or '_'}: {ty(a.get('type'))}" for a in m.findall("arg") if a.get("direction", "in") == "in")
                outs = ", ".join(f"{a.get('name') or '_'}: {ty(a.get('type'))}" for a in m.findall("arg") if a.get("direction") == "out")
                sig = f"({ins})" + (f" → {outs}" if outs else "")
                out.append(f"| `{m.get('name')}` | {sig} | {d} |\n")

# descriptions for members that no longer exist are as wrong as missing ones
known = {f"{n}.{m.get('name')}" for n in ORDER for m in next(i for i in ET.parse(root / f'interfaces/org.kmixdeck1.{n}.xml').getroot().iter('interface')) if m.tag in ("property", "method", "signal")}
stale = [f"{n}.{k}" for n, d in desc.items() for k in d if not k.startswith("_") and f"{n}.{k}" not in known]

if "--write" in sys.argv:
    (root / "docs/dbus-api.md").write_text("".join(out)); print(f"docs/dbus-api.md written: {total - len(missing)}/{total} documented")
else:
    print(f"D-Bus doc: {total - len(missing)}/{total} members documented")
if missing: print("UNDOCUMENTED:", *missing, sep="\n  ")
if stale: print("STALE (no such member):", *stale, sep="\n  ")
sys.exit(1 if (missing or stale) else 0)
