// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 kmixdeck contributors
#include "layout.h"
#include "mixer.h"
#include <QStandardPaths>
#include <QDir>
#include <QFile>
#include <QSaveFile>
#include <QJsonDocument>
#include <QJsonArray>

namespace kmixdeck {

QString Layout::defaultPath() { return QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + QStringLiteral("/kmixdeck/layout.json"); }
QString Layout::defaultPipewireConfPath() { return QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + QStringLiteral("/pipewire/pipewire.conf.d/90-kmixdeck.conf"); }

Layout Layout::starter() {
    Layout l;
    l.channels = {{QStringLiteral("game"), QStringLiteral("Game"), QStringLiteral("input-gaming")},
                  {QStringLiteral("system"), QStringLiteral("System"), QStringLiteral("computer")},
                  {QStringLiteral("voice"), QStringLiteral("Voice"), QStringLiteral("audio-input-microphone")}};
    l.mixes = {{QStringLiteral("monitor"), QStringLiteral("Monitor"), QStringLiteral("audio-headphones"), {}},
               {QStringLiteral("stream"), QStringLiteral("Stream"), QStringLiteral("camera-video"), {}}};
    return l;
}

LayoutChannel *Layout::channel(const QString &slug) { for (auto &c : channels) if (c.slug == slug) return &c; return nullptr; }
LayoutMix *Layout::mix(const QString &slug) { for (auto &m : mixes) if (m.slug == slug) return &m; return nullptr; }
const LayoutChannel *Layout::channel(const QString &slug) const { for (const auto &c : channels) if (c.slug == slug) return &c; return nullptr; }
const LayoutMix *Layout::mix(const QString &slug) const { for (const auto &m : mixes) if (m.slug == slug) return &m; return nullptr; }

QJsonObject Layout::toJson() const {
    QJsonArray ch, mx;
    for (const auto &c : channels) ch.append(QJsonObject{{QStringLiteral("slug"), c.slug}, {QStringLiteral("name"), c.name}, {QStringLiteral("icon"), c.icon}});
    for (const auto &m : mixes) mx.append(QJsonObject{{QStringLiteral("slug"), m.slug}, {QStringLiteral("name"), m.name}, {QStringLiteral("icon"), m.icon}, {QStringLiteral("outputDevice"), m.outputDevice}});
    return {{QStringLiteral("version"), 1}, {QStringLiteral("channels"), ch}, {QStringLiteral("mixes"), mx}};
}
Layout Layout::fromJson(const QJsonObject &o) {
    Layout l;
    for (const auto &v : o.value(QStringLiteral("channels")).toArray()) { const auto c = v.toObject(); l.channels.push_back({c.value(QStringLiteral("slug")).toString(), c.value(QStringLiteral("name")).toString(), c.value(QStringLiteral("icon")).toString()}); }
    for (const auto &v : o.value(QStringLiteral("mixes")).toArray()) { const auto m = v.toObject(); l.mixes.push_back({m.value(QStringLiteral("slug")).toString(), m.value(QStringLiteral("name")).toString(), m.value(QStringLiteral("icon")).toString(), m.value(QStringLiteral("outputDevice")).toString()}); }
    return l;
}
bool Layout::load(const QString &path) {
    QFile f(path); if (!f.open(QIODevice::ReadOnly)) return false;
    QJsonParseError err; const auto doc = QJsonDocument::fromJson(f.readAll(), &err);
    if (err.error != QJsonParseError::NoError || !doc.isObject()) return false;   // DV-6: corrupt config → caller keeps the old layout
    *this = fromJson(doc.object()); return true;
}
bool Layout::save(const QString &path) const {
    QDir().mkpath(QFileInfo(path).absolutePath());
    QSaveFile f(path); if (!f.open(QIODevice::WriteOnly)) return false;
    f.write(QJsonDocument(toJson()).toJson(QJsonDocument::Indented)); return f.commit();
}

static QString q(const QString &s) { QString r = s; r.replace(QLatin1Char('\\'), QLatin1String("\\\\")).replace(QLatin1Char('"'), QLatin1String("\\\"")); return QLatin1Char('"') + r + QLatin1Char('"'); }

QString Layout::toPipewireConf() const {
    QString out;
    out += QStringLiteral("# Generated by kmixdeckd — do not edit; change the layout through kmixdeck/kmixdeck-kde instead.\n"
                          "# ADR 0002: channel = null sink, mix = null sink, cell = loopback whose playback volume is the fader.\n"
                          "# Every loopback has node.dont-fallback so a missing target never silently becomes the default sink (feedback).\n"
                          "# Unrouted mix outputs park on kmixdeck.null (a loopback whose target is missing would die).\n\n");
    out += QStringLiteral("context.objects = [\n");
    // Parking sink for unrouted mix outputs. A loopback whose target does not exist DIES ("defined target not
    // found", module-loopback.c) — so "no output" must still be a real, silent sink. priority.session = 0 and
    // node.passive keep WirePlumber from ever choosing it as default.
    out += QStringLiteral("  { factory = adapter args = { factory.name = support.null-audio-sink node.name = \"kmixdeck.null\" media.name = \"kmixdeck.null\" node.description = \"kmixdeck (unrouted)\" media.class = Audio/Sink object.linger = true audio.position = [ FL FR ] priority.session = 0 priority.driver = 0 node.passive = true } }\n");
    for (const auto &c : channels)
        out += QStringLiteral("  { factory = adapter args = { factory.name = support.null-audio-sink node.name = %1 media.name = %1 node.description = %2 media.class = Audio/Sink object.linger = true audio.position = [ FL FR ] monitor.channel-volumes = true node.passive = true } }\n")
                   .arg(q(Names::channelNode(c.slug)), q(c.name));
    for (const auto &m : mixes)
        out += QStringLiteral("  { factory = adapter args = { factory.name = support.null-audio-sink node.name = %1 media.name = %1 node.description = %2 media.class = Audio/Sink object.linger = true audio.position = [ FL FR ] monitor.channel-volumes = true } }\n")
                   .arg(q(Names::mixNode(m.slug)), q(QStringLiteral("Mix: ") + m.name));
    out += QStringLiteral("]\n\ncontext.modules = [\n");
    // %6 = extra playback props. Cells: dont-reconnect (a cell must never wander). Mix outputs: NO dont-reconnect —
    // WirePlumber (linking/prepare-link.lua) ignores every new target.object once a dont-reconnect stream was linked,
    // and the output has to follow Mix.OutputDevice live. dont-fallback stays on both (never the default sink).
    const QString loop = QStringLiteral(
        "  { name = libpipewire-module-loopback args = { node.description = %1 "
        "capture.props = { node.name = %2 media.name = %2 node.target = %3 stream.capture.sink = true node.passive = true node.dont-reconnect = true node.dont-fallback = true } "
        "playback.props = { node.name = %4 media.name = %4 node.target = %5 node.dont-fallback = true %6} } }\n");
    for (const auto &c : channels)
        for (const auto &m : mixes) {
            const QString cell = Names::cellNode(c.slug, m.slug);
            out += loop.arg(q(c.name + QStringLiteral(" → ") + m.name), q(cell + QStringLiteral(".in")), q(Names::channelNode(c.slug)), q(cell), q(Names::mixNode(m.slug)), QStringLiteral("node.dont-reconnect = true "));
        }
    for (const auto &m : mixes) {
        // hardware output (if configured) — target is the device's node.name, unlinked otherwise
        const QString outNode = QStringLiteral("kmixdeck.out.") + m.slug;
        out += loop.arg(q(QStringLiteral("Mix: ") + m.name + QStringLiteral(" → output")), q(outNode + QStringLiteral(".in")), q(Names::mixNode(m.slug)), q(outNode),
                        q(m.outputDevice.isEmpty() ? QStringLiteral("kmixdeck.null") : m.outputDevice), QString());
        // virtual capture source so OBS/Discord can pick this mix as an input (MX-3b)
        const QString src = QStringLiteral("kmixdeck.source.") + m.slug;
        out += QStringLiteral("  { name = libpipewire-module-loopback args = { node.description = %1 "
                              "capture.props = { node.name = %2 media.name = %2 node.target = %3 stream.capture.sink = true node.passive = true node.dont-reconnect = true node.dont-fallback = true } "
                              "playback.props = { node.name = %4 media.name = %4 node.description = %5 media.class = Audio/Source audio.position = [ FL FR ] } } }\n")
                   .arg(q(QStringLiteral("Mix: ") + m.name + QStringLiteral(" (capture)")), q(src + QStringLiteral(".in")), q(Names::mixNode(m.slug)), q(src), q(QStringLiteral("kmixdeck ") + m.name + QStringLiteral(" Mix")));
    }
    out += QStringLiteral("]\n");
    return out;
}
bool Layout::writePipewireConf(const QString &path) const {
    QDir().mkpath(QFileInfo(path).absolutePath());
    QSaveFile f(path); if (!f.open(QIODevice::WriteOnly)) return false;
    f.write(toPipewireConf().toUtf8()); return f.commit();
}

} // namespace kmixdeck
